name = "FindingTypeAny"
uuid = "92f7b687-d254-4930-b00b-67cec6cf08e3"
authors = ["cometscome <cometscome@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
